TestWeb1/Controllers/FormController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestWeb1.Controllers
{
    public class FormController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TestWeb1/Controllers/HRController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestWeb1.Models;

namespace TestWeb1.Controllers
{
    public class HRController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public List<EmpModel> GetEmpsModel()
        {
            List<EmpModel> emps = new List<EmpModel>();

            EmpModel emp = new EmpModel()
            {
                name = "TEST",
                position = "Technician",
                arrived = DateTime.Parse("2005-05-05 08:30 AM"),
                depart_time = DateTime.Parse("2005-05-05 05:30 PM"),
                absent = 1,
                late = 2,
            };
            emps.Add(emp);

            EmpModel emp2 = new EmpModel();
            emp2.name = "TEST2";
            emp2.position = "Technician";
            emp2.arrived = DateTime.Parse("2005-05-05 08:30 AM");
            emp2.depart_time = DateTime.Parse("2005-05-05 05:30 PM");
            emp2.absent = 1;
            emp2.late = 2;
            emps.Add(emp2);

            return emps;
        }

        [HttpGet]
        public JsonResult GetData()
        {
            List<EmpModel> emps = new List<EmpModel>();
            emps = GetEmpsModel();
            return Json(emps);
        }


    }
}

TestWeb1/Controllers/KanbanController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestWeb1.Models;

namespace TestWeb1.Controllers
{
    public class KanbanController : Controller
    {
        public static List<TaskModel> tasks = new List<TaskModel>();

        public IActionResult Index()
        {
            return View();
        }

        public List<TaskModel> GetTaskModels()
        {
            List<TaskModel> ts = new List<TaskModel>();
            TaskModel task_1 = new TaskModel
            {
                id = "T0001",
                name = "Design Website",
                status = "To_Do"
            };
            ts.Add(task_1);
            TaskModel task_2 = new TaskModel
            {
                id = "T0002",
                name = "Design App",
                status = "To_Do"
            };
            ts.Add(task_2);
            TaskModel task_3 = new TaskModel
            {
                id = "T0003",
                name = "Design Database",
                status = "To_Do"
            };
            ts.Add(task_3);
            return ts;
        }

        [HttpGet]
        public JsonResult SetTasks()
        {
            tasks = GetTaskModels();
            return Json(tasks);
        }

        [HttpGet]
        public JsonResult GetTasks()
        {
            return Json(tasks);
        }

        [HttpPost]
        public JsonResult SetTaskToDo(string id_task)
        {
            foreach(var task in tasks)
            {
                if (task.id == id_task)
                    task.status = "To_Do";
            }
            return Json(id_task + " Successfully Updated");
        }

        [HttpPost]
        public JsonResult SetTaskInProgress(string id_task)
        {
            foreach (var task in tasks)
            {
                if (task.id == id_task)
                    task.status = "In_Progress";
            }
            return Json(id_task + " Successfully Updated");
        }

        [HttpPost]
        public JsonResult SetTaskDone(string id_task)
        {
            foreach (var task in tasks)
            {
                if (task.id == id_task)
                    task.status = "Done";
            }
            return Json(id_task + " Successfully Updated");
        }
    }
}

TestWeb1/Controllers/StockController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using TestWeb1.Interfaces;
using TestWeb1.Models;
using TestWeb1.Services;

namespace TestWeb1.Controllers
{
    public class StockController : Controller
    {
        IDatabase DatabaseInterface;

        public StockController()
        {
            this.DatabaseInterface = new DatabaseService();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetData()
        {
            List<StockModel> stocks = new List<StockModel>();
            stocks = GetStockModels();
            return Json(stocks);
        }

        public List<StockModel> GetStockModels()
        {
            List<StockModel> stocks = new List<StockModel>();
            SqlConnection con = DatabaseInterface.Connect();
            con.Open();
            string str_cmd = "select * from CTL_HQ";
            SqlCommand cmd = new SqlCommand(str_cmd, con);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    StockModel stock = new StockModel()
                    {
                        id = dr["No.1"] != DBNull.Value ? dr["No.1"].ToString() : "",
                        description = dr["Description"] != DBNull.Value ? dr["Description"].ToString() : "",
                        price = ((dr["Price"] != DBNull.Value) && (dr["Price"].ToString() != "")) ? Convert.ToDouble(dr["Price"]) : 0,
                        stock_quantity_hq = dr["Stock Quantity"] != DBNull.Value ? Convert.ToInt32(dr["Stock Quantity"]) : 0,
                        stock_location_hq = dr["Stock Location"] != DBNull.Value ? dr["Stock Location"].ToString() : "",
                        stock_quantity_rbo = dr["Stock Quantity RBO"] != DBNull.Value ? Convert.ToInt32(dr["Stock Quantity RBO"]) : 0,
                        stock_location_rbo = dr["Stock Location RBO"] != DBNull.Value ? dr["Stock Location RBO"].ToString() : "",
                        stock_quantity_kbo = dr["Stock Quantity KBO"] != DBNull.Value ? Convert.ToInt32(dr["Stock Quantity KBO"]) : 0,
                        stock_location_kbo = dr["Stock Location KBO"] != DBNull.Value ? dr["Stock Location KBO"].ToString() : "",
                        unit = dr["Unit"] != DBNull.Value ? dr["Unit"].ToString() : "",
                    };
                    stocks.Add(stock);
                }
                dr.Close();
            }
            con.Close();
            return stocks;
        }
    }
}

TestWeb1/Views/Shared/Footer.cshtml
<!-- Main Footer -->
<footer class="main-footer bg-dark">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

TestWeb1/Views/Shared/LeftMenu.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">
                        <i class="nav-icon fas fa-home"></i>
                        <p>Home</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Calendar" asp-action="Index">
                        <i class="nav-icon fas fa-calendar"></i>
                        <p>Calendar</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="DragnDrop" asp-action="Index">
                        <i class="nav-icon fas fa-hand-point-down"></i>
                        <p>Drag and Drop</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Form" asp-action="Index">
                        <i class="nav-icon fas fa-pen-alt"></i>
                        <p>Form</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Kanban" asp-action="Index">
                        <i class="nav-icon fas fa-table"></i>
                        <p>Kanban</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="KanbanView" asp-action="Index">
                        <i class="nav-icon fas fa-table"></i>
                        <p>KanbanView</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="HR" asp-action="Index">
                        <i class="nav-icon fas fa-table"></i>
                        <p>HR</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Stock" asp-action="Index">
                        <i class="nav-icon fas fa-warehouse"></i>
                        <p>Stock</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="StockRBO" asp-action="Index">
                        <i class="nav-icon fas fa-warehouse"></i>
                        <p>Stock RBO</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="StockKBO" asp-action="Index">
                        <i class="nav-icon fas fa-warehouse"></i>
                        <p>Stock KBO</p>
                    </a>
                </li>

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

TestWeb1/Views/Shared/Script.cshtml
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="~/js/adminlte.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="~/plugins/toastr/toastr.min.js"></script>
<script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
<script src="~/lib/fullcalendar-5.8.0/main.min.js"></script>
<script src="~/lib/fullcalendar-5.8.0/locales-all.min.js"></script>

TestWeb1/Views/Shared/Style.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css" />
<link rel="stylesheet" href="~/css/adminlte.min.css" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css" type="text/css" />
<link rel="stylesheet" href="~/plugins/toastr/toastr.min.css" />
<link rel="stylesheet" href="~/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css" />
<link rel="stylesheet" href="~/lib/fullcalendar-5.8.0/main.min.css" />

TestWeb1/Views/Shared/TopMenu.cshtml
<nav class="main-header navbar navbar-expand navbar-dark navbar-gray-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" asp-controller="Home" asp-action="Index">
                Home
            </a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
</nav>

TestWeb1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Design Example</title>
    <partial name="Style.cshtml" />
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">
        <partial name="TopMenu.cshtml" />
        <partial name="LeftMenu.cshtml" />
        <div class="content-wrapper" style="background-color:rgb(34,39,42)">
            <div class="content">
                @RenderBody()
            </div>
        </div>
        <partial name="Footer.cshtml" />
    </div>
    <partial name="Script.cshtml" />
    @RenderSection("Scripts", required: false)
</body>
</html>