TestWeb1/Controllers/StockKBOController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using TestWeb1.Interfaces;
using TestWeb1.Models;
using TestWeb1.Services;

namespace TestWeb1.Controllers
{
    public class StockKBOController : Controller
    {
        IDatabase DatabaseInterface;

        public StockKBOController()
        {
            this.DatabaseInterface = new DatabaseService();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetData()
        {
            List<StockModel> stocks = new List<StockModel>();
            stocks = GetStockModels();
            return Json(stocks);
        }

        public List<StockModel> GetStockModels()
        {
            List<StockModel> stocks = new List<StockModel>();
            SqlConnection con = DatabaseInterface.ConnectKBO();
            con.Open();
            string str_cmd = "select * from CTL_KBO";
            SqlCommand cmd = new SqlCommand(str_cmd, con);
            SqlDataReader dr = cmd.ExecuteReader();
            if (dr.HasRows)
            {
                while (dr.Read())
                {
                    StockModel stock = new StockModel()
                    {
                        id = dr["No.1"] != DBNull.Value ? dr["No.1"].ToString() : "",
                        description = dr["Description"] != DBNull.Value ? dr["Description"].ToString() : "",
                        price = ((dr["Price"] != DBNull.Value) && (dr["Price"].ToString() != "")) ? Convert.ToDouble(dr["Price"]) : 0,
                        stock_quantity_hq = dr["Stock Quantity"] != DBNull.Value ? Convert.ToInt32(dr["Stock Quantity"]) : 0,
                        stock_location_hq = dr["Stock Location"] != DBNull.Value ? dr["Stock Location"].ToString() : "",
                        stock_quantity_rbo = dr["Stock Quantity RBO"] != DBNull.Value ? Convert.ToInt32(dr["Stock Quantity RBO"]) : 0,
                        stock_location_rbo = dr["Stock Location RBO"] != DBNull.Value ? dr["Stock Location RBO"].ToString() : "",
                        stock_quantity_kbo = dr["Stock Quantity KBO"] != DBNull.Value ? Convert.ToInt32(dr["Stock Quantity KBO"]) : 0,
                        stock_location_kbo = dr["Stock Location KBO"] != DBNull.Value ? dr["Stock Location KBO"].ToString() : "",
                        unit = dr["Unit"] != DBNull.Value ? dr["Unit"].ToString() : "",
                    };
                    stocks.Add(stock);
                }
                dr.Close();
            }
            con.Close();
            return stocks;
        }
    }
}

TestWeb1/Views/StockKBO/Index.cshtml
<div class="container-fluid" style="padding-top:10px">
    <div class="info-box">
        <div class="info-box-content">
            <h3>STOCK KBO</h3>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <span class="card-title">Header</span>
        </div>
        <div class="card-body">
            <table id="table_stock" class="table table-sm table-bordered table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Description</th>
                        <th>Price</th>
                        <th>Unit</th>
                        <th>Stock Quantity HQ</th>
                        <th>Stock Location HQ</th>
                        <th>Stock Quantity RBO</th>
                        <th>Stock Location RBO</th>
                        <th>Stock Quantity KBO</th>
                        <th>Stock Location KBO</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts 
{
    <script type="text/javascript">
        $(document).ready(function () {
            GetStocks();
        });

        function GetStocks() {
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetData", "StockKBO")',
	            contentType: 'application/x-www-form-urlencoded',
                data: { },
                success: function (response) {
                    GenerateTable(response);
                }
            });
        }

        function GenerateTable(stocks) {
            var datas = [];
            for (var i = 0; i < stocks.length; i++) {
                datas.push([
                    stocks[i].id,
                    stocks[i].description,
                    stocks[i].price,
                    stocks[i].unit,
                    stocks[i].stock_quantity_hq,
                    stocks[i].stock_location_hq,
                    stocks[i].stock_quantity_rbo,
                    stocks[i].stock_location_rbo,
                    stocks[i].stock_quantity_kbo,
                    stocks[i].stock_location_kbo
                ]);
            }

            $('#table_stock').DataTable({
                data: datas,
            });
        }

    </script>
}